### ISSUE TITLE
Help??!

### ISSUE THREAD

**Issue by thienha1** [Quackmaster/Grepolis-QT#55]
Can you make scripts that set a timer to automatically pause/stop on all Youtube embed videos? Like pause a video after X seconds!!?

**Comment by Siegfried0** [comment]
Embeded video means possible appearance on all pages over the www.
User scripts normally only works on a few defined ones. You maybe should search for an AddOn instead?
Maybe you can go with something like "[Disable Autoplay for YouTube™](https://addons.mozilla.org/en-US/firefox/addon/disable-autoplay-for-youtube/)"?
